{"name": "Успешное принятие заказа", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?", "trace": "self = <tests.test_accept_order.TestAcceptOrder object at 0x00000284B9516AD0>, setup_courier_and_order = {'courier_id': 615721, 'login': 'cxvurdxxdz', 'order_id': 501018, 'password': 'bwuvkzjiqa', ...}\n\n    @allure.title(\"Успешное принятие заказа\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_accept_order_success(self, setup_courier_and_order):\n        with allure.step(\"Принять заказ валидным курьером\"):\n            response = OrderApi.accept_order(\n                setup_courier_and_order[\"order_id\"],\n                setup_courier_and_order[\"courier_id\"]\n            )\n    \n        with allure.step(\"Проверить код ответа и тело\"):\n>           assert response.status_code == ExpectedResponses.SUCCESS_ACCEPT[\"code\"]\nE           AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?\n\ntests\\test_accept_order.py:22: AttributeError"}, "steps": [{"name": "Принять заказ валидным курьером", "status": "passed", "steps": [{"name": "Принять заказ 501018 курьером 615721", "status": "passed", "parameters": [{"name": "order_id", "value": "501018"}, {"name": "courier_id", "value": "615721"}], "start": 1758527525572, "stop": 1758527526048}], "start": 1758527525572, "stop": 1758527526048}, {"name": "Проверить код ответа и тело", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?\n", "trace": "  File \"C:\\Users\\Пользователь\\sprint_7\\tests\\test_accept_order.py\", line 22, in test_accept_order_success\n    assert response.status_code == ExpectedResponses.SUCCESS_ACCEPT[\"code\"]\n"}, "start": 1758527526048, "stop": 1758527526048}], "start": 1758527525572, "stop": 1758527526050, "uuid": "f2042e1a-943d-4cf2-aa2f-104a3504a63c", "historyId": "bf3d90b089133297733d4bf073c72610", "testCaseId": "bf3d90b089133297733d4bf073c72610", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_success", "labels": [{"name": "epic", "value": "Order Management"}, {"name": "feature", "value": "Accept Order API"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "9396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}