{"name": "Test get order with invalid track", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 400\n +  where 500 = <Response [500]>.status_code", "trace": "self = <tests.test_get_order_by_track.TestGetOrderByTrack object at 0x00000284B95AC640>\n\n    @allure.title(\"Test get order with invalid track\")\n    def test_get_order_invalid_track(self):\n        response = OrderApi.get_order_by_track(\"invalid_track\")\n    \n>       assert response.status_code == 400\nE       assert 500 == 400\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\test_get_order_by_track.py:46: AssertionError"}, "steps": [{"name": "Получить заказ по треку 'invalid_track'", "status": "passed", "parameters": [{"name": "track_id", "value": "'invalid_track'"}], "start": 1758527562789, "stop": 1758527563559}], "start": 1758527562788, "stop": 1758527563560, "uuid": "28fb2bd5-81ca-4a06-8a79-ddad769386a9", "historyId": "e3afb144354bc0591f14a81812069a10", "testCaseId": "e3afb144354bc0591f14a81812069a10", "fullName": "tests.test_get_order_by_track.TestGetOrderByTrack#test_get_order_invalid_track", "labels": [{"name": "feature", "value": "Get Order by Track API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_track"}, {"name": "subSuite", "value": "TestGetOrderByTrack"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "9396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track"}]}