{"name": "Test get order with invalid track", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 400\n +  where 500 = <Response [500]>.status_code", "trace": "self = <tests.test_get_order_by_track.TestGetOrderByTrack object at 0x000001E04C5BC180>\n\n    @allure.title(\"Test get order with invalid track\")\n    def test_get_order_invalid_track(self):\n        response = OrderApi.get_order_by_track(\"invalid_track\")\n    \n>       assert response.status_code == 400\nE       assert 500 == 400\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\test_get_order_by_track.py:46: AssertionError"}, "start": 1758386132173, "stop": 1758386132892, "uuid": "dca05977-5c1d-4346-8581-e8a102447008", "historyId": "e3afb144354bc0591f14a81812069a10", "testCaseId": "e3afb144354bc0591f14a81812069a10", "fullName": "tests.test_get_order_by_track.TestGetOrderByTrack#test_get_order_invalid_track", "labels": [{"name": "feature", "value": "Get Order by Track API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_track"}, {"name": "subSuite", "value": "TestGetOrderByTrack"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "16380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track"}]}