{"name": "Test accept order with invalid courier id", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 400\n +  where 500 = <Response [500]>.status_code", "trace": "self = <tests.test_accept_order.TestAcceptOrder object at 0x000001E04C497490>\n\n    @allure.title(\"Test accept order with invalid courier id\")\n    def test_accept_order_invalid_courier_id(self):\n        response = OrderApi.accept_order(self.order_id, \"invalid_id\")\n    \n>       assert response.status_code == 400\nE       assert 500 == 400\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\test_accept_order.py:48: AssertionError"}, "start": 1758386116829, "stop": 1758386117213, "uuid": "d1ba4908-0cba-416c-8b4d-2226cacc3fe1", "historyId": "7340bb1811a392153b914aaffb7f586b", "testCaseId": "7340bb1811a392153b914aaffb7f586b", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "feature", "value": "Accept Order API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "16380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}